name: firebase_functions_interop
description: Firebase Cloud Functions SDK for Dart written as a JS interop wrapper for official Node.js SDK.
version: 2.2.1
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  js: '>=0.6.7'
  meta: '>=1.1.8'
  dev_test:
  node_interop: '>=2.0.0'
  # node_io: ^1.0.1+2
  # node_http: ^1.0.0
  # firebase_admin_interop:
  firebase_admin_interop:
    git:
      url: https://github.com/tekartikdev/firebase-admin-interop
      ref: dart3a
  tekartik_http_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: http_node
      ref: dart3a
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
dev_dependencies:
  test: ^1.12.0
