name: firebase_functions_interop
description: Firebase Cloud Functions SDK for Dart written as a JS interop wrapper for official Node.js SDK.
version: 2.0.0
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  meta: ^1.1.8
  node_interop: ^2.0.0
  # node_io: ^1.0.1+2
  # node_http: ^1.0.0
  # firebase_admin_interop:
  firebase_admin_interop:
    git:
      url: git://github.com/tekartikdev/firebase-admin-interop
      ref: null_safety
  tekartik_http_node:
    git:
      url: git://github.com/tekartik/common_node.dart
      path: http_node
      ref: null_safety

dev_dependencies:
  test: ^1.12.0
